/**
 * Regenerates the committed Visible gamut table:
 *
 *     npm run generate:gamut
 *
 * The table is an artifact of `core/gamut/optimal-solid.ts` and must never be
 * edited by hand; CI regenerates it and fails on a diff.
 *
 * Run directly by Node, which needs the `.ts` on its imports — the reason the
 * specifiers here and in the generator differ from the app's.
 */

import { writeFileSync } from "node:fs";
import { computeMaxChromaTable } from "../core/gamut/optimal-solid.ts";
import { encodeTable } from "../core/gamut/table.ts";

const destination = new URL(
  "../core/gamut/max-chroma-table.generated.ts",
  import.meta.url,
);

const generated = `/**
 * The Visible gamut boundary: maximum Chroma at 1 degree of Hue by 0.5% of
 * Lightness, as little-endian 16-bit units of 0.00001 Chroma in base64.
 *
 * Generated by \`npm run generate:gamut\` from core/gamut/optimal-solid.ts.
 * Do not edit.
 */

export const MAX_CHROMA_TABLE_BASE64 =
  "${encodeTable(computeMaxChromaTable())}";
`;

writeFileSync(destination, generated);
console.log(`Wrote ${destination.pathname}`);
